### ISSUE TITLE
Add prefix rewriting and prune ns form options

### ISSUE THREAD

**Issue by SevereOverfl0w** [snoe/clj-refactor.nvim#4]
Add a config for clean-ns in the following section:

https://github.com/snoe/clj-refactor.nvim/blob/d92de1648a36737e8f4847fbd4ca9d616663b945/src/clj_refactor/repl.cljs#L90

**Comment by snoe** [comment]
Should now be handled by c7f299a3b4d1ca945837dd615606bcc30b40503a. Thanks

**Comment by snoe** [comment]
Relevant documentation: https://github.com/snoe/clj-refactor.nvim#options
