### ISSUE TITLE
Option to disable cljfmt

### ISSUE THREAD

**Issue by SevereOverfl0w** [snoe/clj-refactor.nvim#6]
My codebase doesn't use the same rules as cljfmt, so I have to go unformat the entire file after every refactor.

Configs for cljfmt (both in style and enabled/disabled) would be great.

Related, do we still need it as an automatic operation? Is there anywhere that the refactored form is any different?

**Comment by snoe** [comment]
It's currently a hack that reformats the whole file - almost every form that's refactored however does need to be formatted in context otherwise things like parinfer will rewrite it. 

What configs do you need?

**Comment by SevereOverfl0w** [comment]
Sorry again for the delayed reply.

Only formatting the code returned from the transform is on the mark for what I needed, thanks!
